package com.chronyx.mcap.internal

/**
 * Supplies the serialized `FileDescriptorSet` (built by protoc with `--include_imports`) that backs
 * every protobuf MCAP Schema record. The same descriptor set contains all CHRONYX + Foxglove message
 * types and their dependencies (incl. `google.protobuf.Timestamp`); Foxglove resolves each schema by
 * the message's full name within the set, so we embed the whole set per schema. The redundancy is a
 * few KB and keeps the writer free of per-type descriptor extraction.
 */
object SchemaRegistry {
    /** Full names of the protobuf messages used as MCAP schemas. */
    const val COMPRESSED_VIDEO = "foxglove.CompressedVideo"
    const val LOCATION_FIX = "foxglove.LocationFix"
    const val CAMERA_CALIBRATION = "foxglove.CameraCalibration"
    const val DEVICE_INFO = "chronyx.DeviceInfo"
    const val IMU_INTRINSICS = "chronyx.ImuIntrinsics"
    const val CAMERA_META = "chronyx.CameraMeta"
    const val IMU_SAMPLE = "chronyx.ImuSample"
    const val GNSS_RAW = "chronyx.GnssRawEpoch"
    const val AUDIO_CHUNK = "chronyx.AudioChunk"
    const val DIAGNOSTICS = "chronyx.SyncDiagnostics"
    const val MARKER = "chronyx.Marker"

    private const val RESOURCE = "chronyx_schemas.desc"

    val descriptorSet: ByteArray by lazy {
        (SchemaRegistry::class.java.classLoader ?: ClassLoader.getSystemClassLoader())
            .getResourceAsStream(RESOURCE)
            ?.use { it.readBytes() }
            ?: error(
                "Missing $RESOURCE on the classpath. It is generated by the protobuf plugin's " +
                    "descriptor-set task into generated/descriptors and packaged as a resource; " +
                    "ensure :chronyx-mcap protobuf generation ran.",
            )
    }
}
